### ISSUE TITLE
Time bug

### ISSUE THREAD

**Issue by kirai** [kirai/destiny-sulfaters#1]

**Comment by zordor** [comment]
Esta mierda es inaceptable, lo quiero arreglado ya!

**Comment by kirai** [comment]
This is been pending for months now

**Comment by CaDs** [comment]
:8ball:

**Comment by CaDs** [comment]
I've checked that there are no issues with the data provided by the API and the one displayed.
I saw though that there is a significant delay between the time in minutes obtained though the API and the ones Bungie is displaying on their profile pages.

So ....
![magic](http://weknowgifs.com/wp-content/uploads/2013/03/its-magic-shia-labeouf-gif.gif)

**Comment by CaDs** [comment]
shame on me, I found the bug

**Comment by CaDs** [comment]
fixed on 28a91286124f92200e7232e7519289f6e428e970
